Schema.voices.Add("Combine", "0", "Zero.", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("Combine", "1", "One.", "npc/metropolice/vo/one.wav")
Schema.voices.Add("Combine", "10", "Ten.", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("Combine", "10-0 HUNTING", "10-0, 10-0, viscerator is hunting!", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
Schema.voices.Add("Combine", "100", "One-hundred.", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("Combine", "10-103 TAG", "Possible 10-103, my location, alert TAG units.", "npc/metropolice/vo/possible10-103alerttagunits.wav")
Schema.voices.Add("Combine", "10-107", "I have a 10-107 here, send AirWatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
Schema.voices.Add("Combine", "10-108", "We have a 10-108!", "npc/metropolice/vo/wehavea10-108.wav")
Schema.voices.Add("Combine", "10-14", "Holding on 10-14 duty, eh, code four.", "npc/metropolice/vo/holdingon10-14duty.wav")
Schema.voices.Add("Combine", "10-15", "Prepare for 10-15.", "npc/metropolice/vo/preparefor1015.wav")
Schema.voices.Add("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("Combine", "10-25", "Any unit, report in with 10-25 as suspect.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
Schema.voices.Add("Combine", "10-30", "I have a 10-30, my 10-20, responding, code two.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav")
Schema.voices.Add("Combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
Schema.voices.Add("Combine", "10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav")
Schema.voices.Add("Combine", "10-78", "Dispatch, I need 10-78, officer in trouble!", "npc/metropolice/vo/dispatchIneed10-78.wav")
Schema.voices.Add("Combine", "10-8 standing by", "10-8, standing by.", "npc/metropolice/vo/ten8standingby.wav")
Schema.voices.Add("Combine", "10-8", "Unit is on-duty, 10-8.", "npc/metropolice/vo/unitisonduty10-8.wav")
Schema.voices.Add("Combine", "10-91D", "10-91d count is...", "npc/metropolice/vo/ten91dcountis.wav")
Schema.voices.Add("Combine", "10-97 GOA", "10-97, that suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav")
Schema.voices.Add("Combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
Schema.voices.Add("Combine", "10-99", "Officer down, I am 10-99, I repeat, I am 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav")
Schema.voices.Add("Combine", "11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
Schema.voices.Add("Combine", "11-6", "Suspect 11-6, my 10-20 is...", "npc/metropolice/vo/suspect11-6my1020is.wav")
Schema.voices.Add("Combine", "11-99", "11-99, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
Schema.voices.Add("Combine", "2", "Two.", "npc/metropolice/vo/two.wav")
Schema.voices.Add("Combine", "20", "Twenty.", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("Combine", "200", "Two-hundred.", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("Combine", "3", "Three.", "npc/metropolice/vo/three.wav")
Schema.voices.Add("Combine", "30", "Thirty.", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("Combine", "300", "Three-hundred.", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("Combine", "34S AT", "All units, BOL, we have 34-S at...", "npc/metropolice/vo/allunitsbol34sat.wav")
Schema.voices.Add("Combine", "4", "Four.", "npc/metropolice/vo/four.wav")
Schema.voices.Add("Combine", "40", "Fourty.", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("Combine", "404", "404 zone.", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("Combine", "408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav")
Schema.voices.Add("Combine", "415B", "Is 415b.", "npc/metropolice/vo/is415b.wav")
Schema.voices.Add("Combine", "5", "Five.", "npc/metropolice/vo/five.wav")
Schema.voices.Add("Combine", "50", "Fifty.", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("Combine", "505", "Dispatch, we need AirWatch, subject is 505!", "npc/metropolice/vo/airwatchsubjectis505.wav")
Schema.voices.Add("Combine", "6", "Six.", "npc/metropolice/vo/six.wav")
Schema.voices.Add("Combine", "60", "Sixty.", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("Combine", "603", "603, unlawful entry.", "npc/metropolice/vo/unlawfulentry603.wav")
Schema.voices.Add("Combine", "63", "63, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav")
Schema.voices.Add("Combine", "7", "Seven.", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("Combine", "70", "Seventy.", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("Combine", "8", "Eight.", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("Combine", "80", "Eighty.", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("Combine", "9", "Nine.", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("Combine", "90", "Ninety.", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("Combine", "THAT'S A GRENADE", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav")
Schema.voices.Add("Combine", "ACQUIRING", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav")
Schema.voices.Add("Combine", "ADMINISTER", "Administer.", "npc/metropolice/vo/administer.wav")
Schema.voices.Add("Combine", "CONFIRMED ADW", "Confirmed as ADW on that suspect, 10-0.", "npc/metropolice/vo/confirmadw.wav")
Schema.voices.Add("Combine", "AFFIRMATIVE", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("Combine", "ALL UNITS MOVE", "All units, move in!", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("Combine", "AMPUTATE", "Amputate.", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("Combine", "ANTICITIZEN", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("Combine", "ANTISEPTIC", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav")
Schema.voices.Add("Combine", "APEX", "Apex.", "npc/combine_soldier/vo/apex.wav")
Schema.voices.Add("Combine", "APPLY", "Apply.", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("Combine", "ARREST POSITIONS", "All units, move to arrest positions!", "npc/metropolice/vo/movetoarrestpositions.wav")
Schema.voices.Add("Combine", "AT CHECKPOINT", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
Schema.voices.Add("Combine", "AT LOCATION REPORT", "Protection-teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav")
Schema.voices.Add("Combine", "BACK ME UP", "Back me up, I'm out!", "npc/metropolice/vo/backmeupImout.wav")
Schema.voices.Add("Combine", "BACKUP", "Backup!", "npc/metropolice/vo/backup.wav")
Schema.voices.Add("Combine", "BLADE", "Blade.", "npc/combine_soldier/vo/blade.wav")
Schema.voices.Add("Combine", "BLEEDING", "Suspect is bleeding from multiple wounds!", "npc/metropolice/vo/suspectisbleeding.wav")
Schema.voices.Add("Combine", "BLIP", "Catch that blip on the stabilization readout?", "npc/metropolice/vo/catchthatbliponstabilization.wav")
Schema.voices.Add("Combine", "BLOCK HOLDING", "Block is holding, cohesive.", "npc/metropolice/vo/blockisholdingcohesive.wav")
Schema.voices.Add("Combine", "BLOCK", "Block!", "npc/metropolice/vo/block.wav")
Schema.voices.Add("Combine", "BOL 243", "CP, we need AirWatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav")
Schema.voices.Add("Combine", "BOOMER", "Boomer.", "npc/combine_soldier/vo/boomer.wav")
Schema.voices.Add("Combine", "BREAK COVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("Combine", "CAN1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav")
Schema.voices.Add("Combine", "CAN2", "Pick up the can!", "npc/metropolice/vo/pickupthecan2.wav")
Schema.voices.Add("Combine", "CAN3", "I said, pick up the can!", "npc/metropolice/vo/pickupthecan3.wav")
Schema.voices.Add("Combine", "CAN4", "Now, put it in the trash-can.", "npc/metropolice/vo/putitinthetrash1.wav")
Schema.voices.Add("Combine", "CAN5", "I said, put it in the trash-can!", "npc/metropolice/vo/putitinthetrash2.wav")
Schema.voices.Add("Combine", "CAN6", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav")
Schema.voices.Add("Combine", "CANAL", "Canal.", "npc/metropolice/vo/canal.wav")
Schema.voices.Add("Combine", "CANALBLOCK", "Canalblock!", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("Combine", "CAUTERIZE", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("Combine", "CHECK MISCOUNT", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("Combine", "CHECKPOINTS", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav")
Schema.voices.Add("Combine", "CITIZEN SUMMONED", "Reporting citizen summoned into voluntary conscription for channel open service detail T94-332.", "npc/metropolice/vo/citizensummoned.wav")
Schema.voices.Add("Combine", "CITIZEN", "Citizen.", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("Combine", "CLASSIFY DB", "Classify subject name as 'DB'; this block ready for clean-out.", "npc/metropolice/vo/classifyasdbthisblockready.wav")
Schema.voices.Add("Combine", "CLEANED", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav")
Schema.voices.Add("Combine", "CLEAR CODE 100", "Clear and code one-hundred.", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("Combine", "CLOSE ON SUSPECT", "All units, close on suspect!", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("Combine", "CLOSING", "Closing!", {"npc/combine_soldier/vo/closing.wav", "npc/combine_soldier/vo/closing2.wav"})
Schema.voices.Add("Combine", "CODE 100", "Code one-hundred.", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("Combine", "CODE 2", "All units, code two!", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("Combine", "CODE 3", "Officer down, request all units, code three to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
Schema.voices.Add("Combine", "CODE 7", "Code seven.", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("Combine", "CONDEMNED", "Condemned zone!", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("Combine", "CONTACT 243", "Contact with 243 suspect, my 10-20 is...", "npc/metropolice/vo/contactwith243suspect.wav")
Schema.voices.Add("Combine", "CONTACT PRIORITY", "I have contact with a priority two!", "npc/metropolice/vo/contactwithpriority2.wav")
Schema.voices.Add("Combine", "CONTACT", "Contact!", "npc/combine_soldier/vo/contact.wav")
Schema.voices.Add("Combine", "CONTAINED", "Contained.", "npc/combine_soldier/vo/contained.wav")
Schema.voices.Add("Combine", "CONTROL 100", "Control is one-hundred percent this location, no sign of that 647-E.", "npc/metropolice/vo/control100percent.wav")
Schema.voices.Add("Combine", "CONTROLSECTION", "Control-section!", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("Combine", "CONVERGING", "Converging.", "npc/metropolice/vo/converging.wav")
Schema.voices.Add("Combine", "COPY THAT", "Copy that.", "npc/combine_soldier/vo/copythat.wav")
Schema.voices.Add("Combine", "COPY", "Copy.", "npc/metropolice/vo/copy.wav")
Schema.voices.Add("Combine", "COVER", "Cover!", "npc/combine_soldier/vo/coverhurt.wav")
Schema.voices.Add("Combine", "CP COMPROMISED", "CP is compromised, re-establish!", "npc/metropolice/vo/cpiscompromised.wav")
Schema.voices.Add("Combine", "CP ESTABLISH", "CP, we need to establish our perimeter at...", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
Schema.voices.Add("Combine", "CP OVERRUN", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
Schema.voices.Add("Combine", "DAGGER", "Dagger.", "npc/combine_soldier/vo/dagger.wav")
Schema.voices.Add("Combine", "DASH", "Dash.", "npc/combine_soldier/vo/dash.wav")
Schema.voices.Add("Combine", "DB COUNT", "DB count is...", "npc/metropolice/vo/dbcountis.wav")
Schema.voices.Add("Combine", "DEFENDER", "Defender!", "npc/metropolice/vo/defender.wav")
Schema.voices.Add("Combine", "DESERVICED AREA", "Deserviced area.", "npc/metropolice/vo/deservicedarea.wav")
Schema.voices.Add("Combine", "DESIGNATE SUSPECT", "Designate suspect as...", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("Combine", "DESTROY COVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("Combine", "DISLOCATE INTERPOSE", "Fire to dislocate that interpose!", "npc/metropolice/vo/firetodislocateinterpose.wav")
Schema.voices.Add("Combine", "DISMOUNTING HARDPOINT", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
Schema.voices.Add("Combine", "DISP APB", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav")
Schema.voices.Add("Combine", "DISTRIBUTION BLOCK", "Distribution block.", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("Combine", "DOCUMENT", "Document.", "npc/metropolice/vo/document.wav")
Schema.voices.Add("Combine", "DONT MOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav")
Schema.voices.Add("Combine", "ECHO", "Echo.", "npc/combine_soldier/vo/echo.wav")
Schema.voices.Add("Combine", "ENGAGING", "Engaging!", "npc/combine_soldier/vo/engaging.wav")
Schema.voices.Add("Combine", "ESTABLISH NEW CP", "Fall down, establish a new CP!", "npc/metropolice/vo/establishnewcp.wav")
Schema.voices.Add("Combine", "EXPOSE TARGET", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
Schema.voices.Add("Combine", "EXTERNAL", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav")
Schema.voices.Add("Combine", "FINAL VERDICT", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
Schema.voices.Add("Combine", "FINAL WARNING", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
Schema.voices.Add("Combine", "FIRST WARNING", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
Schema.voices.Add("Combine", "FIST", "Fist.", "npc/combine_soldier/vo/fist.wav")
Schema.voices.Add("Combine", "FLASH", "Flash.", "npc/combine_soldier/vo/flash.wav")
Schema.voices.Add("Combine", "FLATLINE", "Flatline.", "npc/combine_soldier/vo/flatline.wav")
Schema.voices.Add("Combine", "FLUSH", "Flush.", "npc/combine_soldier/vo/flush.wav")
Schema.voices.Add("Combine", "FREE NECROTICS", "I have free necrotics!", "npc/metropolice/vo/freenecrotics.wav")
Schema.voices.Add("Combine", "GET DOWN", "Get down!", "npc/metropolice/vo/getdown.wav")
Schema.voices.Add("Combine", "GET OUT", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav")
Schema.voices.Add("Combine", "GETTING 647E", "Still getting that 647-E from local surveillance.", "npc/metropolice/vo/stillgetting647e.wav")
Schema.voices.Add("Combine", "GHOST", "Ghost.", "npc/combine_soldier/vo/ghost.wav")
Schema.voices.Add("Combine", "GO AGAIN", "PT, go again.", "npc/metropolice/vo/ptgoagain.wav")
Schema.voices.Add("Combine", "GO SHARP", "Go sharp!", "npc/combine_soldier/vo/gosharp.wav")
Schema.voices.Add("Combine", "GOING IN", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav")
Schema.voices.Add("Combine", "GOT A DB", "Uh, we got a DB here, cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
Schema.voices.Add("Combine", "GOT HIM AGAIN", "Got him again, suspect is 10-20 at...", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
Schema.voices.Add("Combine", "GOT ONE ACCOMPLICE", "I got one accomplice here!", "npc/metropolice/vo/gotoneaccomplicehere.wav")
Schema.voices.Add("Combine", "GOT SUSPECT ONE", "I got suspect one here!", "npc/metropolice/vo/gotsuspect1here.wav")
Schema.voices.Add("Combine", "GRENADE", "Grenade!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("Combine", "GRID", "Grid.", "npc/combine_soldier/vo/grid.wav")
Schema.voices.Add("Combine", "HAHA", "Haha.", "npc/metropolice/vo/chuckle.wav")
Schema.voices.Add("Combine", "HAMMER", "Hammer.", "npc/combine_soldier/vo/hammer.wav")
Schema.voices.Add("Combine", "HARDPOINT PROSECUTE", "Is at hardpoint, ready to prosecute!", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
Schema.voices.Add("Combine", "HARDPOINT SCANNING", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav")
Schema.voices.Add("Combine", "HELIX", "Helix.", "npc/combine_soldier/vo/helix.wav")
Schema.voices.Add("Combine", "HELP", "Help!", "npc/metropolice/vo/help.wav")
Schema.voices.Add("Combine", "HERO", "Hero!", "npc/metropolice/vo/hero.wav")
Schema.voices.Add("Combine", "HES 148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav")
Schema.voices.Add("Combine", "HIGH PRIORITY", "High-priority region.", "npc/metropolice/vo/highpriorityregion.wav")
Schema.voices.Add("Combine", "HOLD IT", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
Schema.voices.Add("Combine", "HOLD POSITION", "Protection-team, hold this position.", "npc/metropolice/vo/holdthisposition.wav")
Schema.voices.Add("Combine", "HOLD", "Hold it!", "npc/metropolice/vo/holdit.wav")
Schema.voices.Add("Combine", "HUNTER", "Hunter.", "npc/combine_soldier/vo/hunter.wav")
Schema.voices.Add("Combine", "HURRICANE", "Hurricane.", "npc/combine_soldier/vo/hurricane.wav")
Schema.voices.Add("Combine", "I SAID MOVE", "I said move along.", "npc/metropolice/vo/Isaidmovealong.wav")
Schema.voices.Add("Combine", "ICE", "Ice.", "npc/combine_soldier/vo/ice.wav")
Schema.voices.Add("Combine", "IN POSITION", "In position.", "npc/metropolice/vo/inposition.wav")
Schema.voices.Add("Combine", "INBOUND", "Inbound.", "npc/combine_soldier/vo/inbound.wav")
Schema.voices.Add("Combine", "INFECTED", "Infected.", "npc/combine_soldier/vo/infected.wav")
Schema.voices.Add("Combine", "INFECTION", "Infection!", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("Combine", "INFESTED", "Infested zone.", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("Combine", "INJECT", "Inject!", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("Combine", "INOCULATE", "Inoculate.", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("Combine", "INTERCEDE", "Intercede!", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("Combine", "INTERLOCK", "Interlock!", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("Combine", "INVESTIGATE", "Investigate.", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("Combine", "INVESTIGATING", "Investigating 10-103.", "npc/metropolice/vo/investigating10-103.wav")
Schema.voices.Add("Combine", "ION", "Ion.", "npc/combine_soldier/vo/ion.wav")
Schema.voices.Add("Combine", "IS 10-108", "Is 10-108!", "npc/metropolice/vo/is10-108.wav")
Schema.voices.Add("Combine", "IS 10-8", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav")
Schema.voices.Add("Combine", "IS CLOSING", "Is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav")
Schema.voices.Add("Combine", "IS DOWN", "Is down!", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("Combine", "IS INBOUND", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav")
Schema.voices.Add("Combine", "IS MOVING IN", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav")
Schema.voices.Add("Combine", "IS MOVING", "Is moving in!", "npc/metropolice/vo/ismovingin.wav")
Schema.voices.Add("Combine", "IS PASSIVE", "Is passive.", "npc/metropolice/vo/ispassive.wav")
Schema.voices.Add("Combine", "IS READY TO GO", "Is ready to go!", "npc/metropolice/vo/isreadytogo.wav")
Schema.voices.Add("Combine", "ISOLATE", "Isolate!", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("Combine", "JET", "Jet.", "npc/combine_soldier/vo/jet.wav")
Schema.voices.Add("Combine", "JUDGE", "Judge.", "npc/combine_soldier/vo/judge.wav")
Schema.voices.Add("Combine", "JUDGMENT", "Suspect, prepare to receive civil judgment!", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("Combine", "JURISDICTION", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
Schema.voices.Add("Combine", "JURY", "Jury!", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("Combine", "KEEP MOVING", "Keep moving!", "npc/metropolice/vo/keepmoving.wav")
Schema.voices.Add("Combine", "KILO", "Kilo.", "npc/combine_soldier/vo/kilo.wav")
Schema.voices.Add("Combine", "KING", "King!", "npc/metropolice/vo/king.wav")
Schema.voices.Add("Combine", "LAST SEEN AT", "Hiding, last seen at range...", "npc/metropolice/vo/hidinglastseenatrange.wav")
Schema.voices.Add("Combine", "LEADER", "Leader.", "npc/combine_soldier/vo/leader.wav")
Schema.voices.Add("Combine", "LEVEL 3", "I have a level three civil-privacy violator here!", "npc/metropolice/vo/level3civilprivacyviolator.wav")
Schema.voices.Add("Combine", "LINE", "Line!", "npc/metropolice/vo/line.wav")
Schema.voices.Add("Combine", "LOCATION", "Location?", "npc/metropolice/vo/location.wav")
Schema.voices.Add("Combine", "LOCK POSITION", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav")
Schema.voices.Add("Combine", "LOCK", "Lock!", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("Combine", "LOOK OUT", "Look out!", "npc/metropolice/vo/lookout.wav")
Schema.voices.Add("Combine", "LOOSE PARASITICS", "Loose parasitics!", "npc/metropolice/vo/looseparasitics.wav")
Schema.voices.Add("Combine", "LOST CONTACT", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav")
Schema.voices.Add("Combine", "LOW ON", "Running low on verdicts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav")
Schema.voices.Add("Combine", "MACE", "Mace.", "npc/combine_soldier/vo/mace.wav")
Schema.voices.Add("Combine", "MAINTAIN CP", "All units, maintain this CP!", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("Combine", "MALCOMPLIANCE", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
Schema.voices.Add("Combine", "MALCOMPLIANT 10-107", "Malcompliant 10-107 at my 10-20, preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav")
Schema.voices.Add("Combine", "MALIGNANT", "Malignant!", "npc/metropolice/vo/malignant.wav")
Schema.voices.Add("Combine", "MATCH ON APB", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav")
Schema.voices.Add("Combine", "MINOR HITS", "Minor hits, continuing prosecution!", "npc/metropolice/vo/minorhitscontinuing.wav")
Schema.voices.Add("Combine", "MOVE ALONG", "Move along!", "npc/metropolice/vo/movealong.wav")
Schema.voices.Add("Combine", "MOVE BACK", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav")
Schema.voices.Add("Combine", "MOVE IN", "Move in!", "npc/combine_soldier/vo/movein.wav")
Schema.voices.Add("Combine", "MOVE IT", "Move it!", "npc/metropolice/vo/moveit.wav")
Schema.voices.Add("Combine", "MOVE", "Move!", "npc/metropolice/vo/move.wav")
Schema.voices.Add("Combine", "MOVING TO COVER", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav")
Schema.voices.Add("Combine", "MOVING TO HARDPOINT", "Moving to hardpoint!", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("Combine", "NECROTICS", "Necrotics!", "npc/metropolice/vo/necrotics.wav")
Schema.voices.Add("Combine", "NEED ANY HELP", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("Combine", "NEEDS ASSISTANCE", "Officer needs assistance, I am 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
Schema.voices.Add("Combine", "NEEDS HELP", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav")
Schema.voices.Add("Combine", "NO 647", "Clear, no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav")
Schema.voices.Add("Combine", "NO CONTACT", "No contact!", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("Combine", "NO I'M GOOD", "No, I'm good.", "vo/trainyard/ba_noimgood.wav")
Schema.voices.Add("Combine", "NO VISUAL ON", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav")
Schema.voices.Add("Combine", "NOMAD", "Nomad.", "npc/combine_soldier/vo/nomad.wav")
Schema.voices.Add("Combine", "NONCITIZEN", "Noncitizen.", "npc/metropolice/vo/noncitizen.wav")
Schema.voices.Add("Combine", "NONPATROL", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("Combine", "NONTAGGED VIROMES", "Non-tagged viromes here!", "npc/metropolice/vo/non-taggedviromeshere.wav")
Schema.voices.Add("Combine", "NOVA", "Nova.", "npc/combine_soldier/vo/nova.wav")
Schema.voices.Add("Combine", "NOW GET OUT", "Now, get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav")
Schema.voices.Add("Combine", "NOW", "Now.", "vo/trainyard/ba_thatbeer01.wav")
Schema.voices.Add("Combine", "OUTBREAK", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav")
Schema.voices.Add("Combine", "OUTBREAK", "Outbreak!", "npc/metropolice/vo/outbreak.wav")
Schema.voices.Add("Combine", "OVERWATCH", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav")
Schema.voices.Add("Combine", "PACIFYING", "Pacifying!", "npc/metropolice/vo/pacifying.wav")
Schema.voices.Add("Combine", "PAIN1", "Ugh!", "npc/metropolice/pain1.wav")
Schema.voices.Add("Combine", "PAIN2", "Uagh!", "npc/metropolice/pain2.wav")
Schema.voices.Add("Combine", "PAIN3", "Augh!", "npc/metropolice/pain3.wav")
Schema.voices.Add("Combine", "PAIN4", "Agh!", "npc/metropolice/pain4.wav")
Schema.voices.Add("Combine", "PATROL", "Patrol!", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("Combine", "PAYBACK", "Payback.", "npc/combine_soldier/vo/payback.wav")
Schema.voices.Add("Combine", "PHANTOM", "Phantom.", "npc/combine_soldier/vo/phantom.wav")
Schema.voices.Add("Combine", "PICKUP 647E", "Anyone else pick up a, uh... 647-E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
Schema.voices.Add("Combine", "POSITION AT HARDPOINT", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav")
Schema.voices.Add("Combine", "POSITION TO CONTAIN", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav")
Schema.voices.Add("Combine", "POSSIBLE 404", "Possible 404 here!", "npc/metropolice/vo/possible404here.wav")
Schema.voices.Add("Combine", "POSSIBLE 647E", "Possible 647-E here, request AirWatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav")
Schema.voices.Add("Combine", "POSSIBLE ACCOMPLICE", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav")
Schema.voices.Add("Combine", "POSSIBLE LEVEL 3", "Possible level three civil-privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
Schema.voices.Add("Combine", "PREPARING TO JUDGE", "Preparing to judge a 10-107, be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav")
Schema.voices.Add("Combine", "PRESERVE", "Preserve!", "npc/metropolice/vo/preserve.wav")
Schema.voices.Add("Combine", "PRESSURE", "Pressure!", "npc/metropolice/vo/pressure.wav")
Schema.voices.Add("Combine", "PRIORITY 1", "Confirm, priority-one sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav")
Schema.voices.Add("Combine", "PRIORITY 2", "I have a priority-two anti-citizen here!", "npc/metropolice/vo/priority2anticitizenhere.wav")
Schema.voices.Add("Combine", "PRODUCTION BLOCK", "Production-block.", "npc/metropolice/vo/productionblock.wav")
Schema.voices.Add("Combine", "PROSECUTE MALCOMPLIANT", "Ready to prosecute malcompliant citizen, final warning issued!", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
Schema.voices.Add("Combine", "PROSECUTE", "Prosecute!", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("Combine", "PROSECUTING", "Prosecuting.", "npc/combine_soldier/vo/prosecuting.wav")
Schema.voices.Add("Combine", "PROTECTION COMPLETE", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav")
Schema.voices.Add("Combine", "QUICK", "Quick!", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("Combine", "QUICKSAND", "Quicksand.", "npc/combine_soldier/vo/quicksand.wav")
Schema.voices.Add("Combine", "RANGE", "Range.", "npc/combine_soldier/vo/range.wav")
Schema.voices.Add("Combine", "RANGER", "Ranger.", "npc/combine_soldier/vo/ranger.wav")
Schema.voices.Add("Combine", "RAZOR", "Razor.", "npc/combine_soldier/vo/razor.wav")
Schema.voices.Add("Combine", "READY AMPUTATE", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav")
Schema.voices.Add("Combine", "READY CHARGES", "Ready charges!", "npc/combine_soldier/vo/readycharges.wav")
Schema.voices.Add("Combine", "READY JUDGE", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav")
Schema.voices.Add("Combine", "READY PROSECUTE", "Ready to prosecute!", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("Combine", "READY WEAPONS", "Ready weapons!", "npc/combine_soldier/vo/readyweapons.wav")
Schema.voices.Add("Combine", "REAPER", "Reaper.", "npc/combine_soldier/vo/reaper.wav")
Schema.voices.Add("Combine", "REINFORCEMENT TEAMS", "Reinforcement-teams, code three!", "npc/metropolice/vo/reinforcementteamscode3.wav")
Schema.voices.Add("Combine", "REPORT CLEAR", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("Combine", "REPORT IN", "CP requests all units, uhh... Location report-in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
Schema.voices.Add("Combine", "REPORT LOCATION", "All units, report location suspect!", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("Combine", "REPORT STATUS", "Local CP-teams, report status.", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("Combine", "REPURPOSED", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav")
Schema.voices.Add("Combine", "RESIDENTIAL BLOCK", "Residential block.", "npc/metropolice/vo/residentialblock.wav")
Schema.voices.Add("Combine", "RESPOND CODE 3", "All units at location, responding code three!", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("Combine", "RESPONDING", "Responding.", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("Combine", "RESTRICT", "Restrict!", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("Combine", "RESTRICTED", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav")
Schema.voices.Add("Combine", "RESTRICTION ZONE", "Terminal restriction-zone!", "npc/metropolice/vo/terminalrestrictionzone.wav")
Schema.voices.Add("Combine", "RIPCORD", "Ripcord!", "npc/combine_soldier/vo/ripcord.wav")
Schema.voices.Add("Combine", "RODGER THAT", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav")
Schema.voices.Add("Combine", "ROLLER", "Roller!", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("Combine", "RUNNING", "He's running!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("Combine", "SACRIFICE CODE", "All units, sacrifice code one and maintain this CP!", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
Schema.voices.Add("Combine", "SAVAGE", "Savage.", "npc/combine_soldier/vo/savage.wav")
Schema.voices.Add("Combine", "SCAR", "Scar.", "npc/combine_soldier/vo/scar.wav")
Schema.voices.Add("Combine", "SEARCH", "Search!", "npc/metropolice/vo/search.wav")
Schema.voices.Add("Combine", "SEARCHING FOR SUSPECT", "Searching for suspect.", "npc/metropolice/vo/searchingforsuspect.wav")
Schema.voices.Add("Combine", "SECOND WARNING", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav")
Schema.voices.Add("Combine", "SECTOR NOT STERILE", "Confirmed- sector not sterile.", "npc/combine_soldier/vo/confirmsectornotsterile.wav")
Schema.voices.Add("Combine", "SECTOR NOT SECURE", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("Combine", "SECURE ADVANCE", "Assault-point secured, advance!", "npc/metropolice/vo/assaultpointsecureadvance.wav")
Schema.voices.Add("Combine", "SECURE", "Secure.", "npc/combine_soldier/vo/secure.wav")
Schema.voices.Add("Combine", "SENTENCE", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav")
Schema.voices.Add("Combine", "SERVE", "Serve.", "npc/metropolice/vo/serve.wav")
Schema.voices.Add("Combine", "SHADOW", "Shadow.", "npc/combine_soldier/vo/shadow.wav")
Schema.voices.Add("Combine", "SHARPZONE", "Sharpzone.", "npc/combine_soldier/vo/sharpzone.wav")
Schema.voices.Add("Combine", "SHIT", "Shit!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("Combine", "SHOTS FIRED", "Shots fired, hostile malignants here!", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
Schema.voices.Add("Combine", "SLAM", "Slam.", "npc/combine_soldier/vo/slam.wav")
Schema.voices.Add("Combine", "SLASH", "Slash.", "npc/combine_soldier/vo/slash.wav")
Schema.voices.Add("Combine", "SOCIOCIDE", "Sociocide.", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("Combine", "SOCIOSTABLE", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav")
Schema.voices.Add("Combine", "SPEAR", "Spear.", "npc/combine_soldier/vo/spear.wav")
Schema.voices.Add("Combine", "STAB", "Stab.", "npc/combine_soldier/vo/stab.wav")
Schema.voices.Add("Combine", "STANDING BY", "Standing by.", "npc/combine_soldier/vo/standingby].wav")
Schema.voices.Add("Combine", "STAR", "Star.", "npc/combine_soldier/vo/star.wav")
Schema.voices.Add("Combine", "STATIONBLOCK", "Stationblock.", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("Combine", "STAY ALERT", "Stay alert.", "npc/combine_soldier/vo/stayalert.wav")
Schema.voices.Add("Combine", "STERILIZE", "Sterilize!", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("Combine", "STINGER", "Stinger.", "npc/combine_soldier/vo/stinger.wav")
Schema.voices.Add("Combine", "STORM", "Storm.", "npc/combine_soldier/vo/storm.wav")
Schema.voices.Add("Combine", "STRIKE", "Striker.", "npc/combine_soldier/vo/striker.wav")
Schema.voices.Add("Combine", "SUBJECT 505", "Subject is 505!", "npc/metropolice/vo/subjectis505.wav")
Schema.voices.Add("Combine", "SUBJECT HIGH SPEED", "All units, be advised, subject is now high-speed!", "npc/metropolice/vo/subjectisnowhighspeed.wav")
Schema.voices.Add("Combine", "SUBJECT", "Subject!", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("Combine", "SUNDOWN", "Sundown.", "npc/combine_soldier/vo/sundown.wav")
Schema.voices.Add("Combine", "SUSPECT INCURSION", "Disp reports suspect-incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav")
Schema.voices.Add("Combine", "SUSPECT MOVED TO", "Suspect has moved now to...", "npc/metropolice/vo/supsecthasmovednowto.wav")
Schema.voices.Add("Combine", "SUSPECT RESTRICTED CANALS", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
Schema.voices.Add("Combine", "SUSPEND", "Suspend!", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("Combine", "SWEEPER", "Sweeper.", "npc/combine_soldier/vo/sweeper.wav")
Schema.voices.Add("Combine", "SWEEPING IN", "Sweeping in!", "npc/combine_soldier/vo/sweepingin.wav")
Schema.voices.Add("Combine", "SWEEPING SUSPECT", "Sweeping for suspect!", "npc/metropolice/vo/sweepingforsuspect.wav")
Schema.voices.Add("Combine", "SWIFT", "Swift.", "npc/combine_soldier/vo/swift.wav")
Schema.voices.Add("Combine", "SWORD", "Sword.", "npc/combine_soldier/vo/sword.wav")
Schema.voices.Add("Combine", "TAG 10-91D", "Tag 10-91d!", "npc/metropolice/vo/tag10-91d.wav")
Schema.voices.Add("Combine", "TAG BUG", "Tag one bug!", "npc/metropolice/vo/tagonebug.wav")
Schema.voices.Add("Combine", "TAG NECROTIC", "Tag one necrotic!", "npc/metropolice/vo/tagonenecrotic.wav")
Schema.voices.Add("Combine", "TAG PARASITIC", "Tag one parasitic!", "npc/metropolice/vo/tagoneparasitic.wav")
Schema.voices.Add("Combine", "TAKE A LOOK", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav")
Schema.voices.Add("Combine", "TAKE COVER", "Take cover!", "npc/metropolice/vo/takecover.wav")
Schema.voices.Add("Combine", "TAP", "Tap!", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("Combine", "TARGET", "Target.", "npc/combine_soldier/vo/target.wav")
Schema.voices.Add("Combine", "TEAM ADVANCE", "Team in position, advance!", "npc/metropolice/vo/teaminpositionadvance.wav")
Schema.voices.Add("Combine", "TEAM HOLDING", "Stabilization team holding in position.", "npc/combine_soldier/vo/stabilizationteamholding.wav")
Schema.voices.Add("Combine", "THERE HE GOES", "There he goes! He's at...", "npc/metropolice/vo/therehegoeshesat.wav")
Schema.voices.Add("Combine", "THERE HE IS", "There he is!", "npc/metropolice/vo/thereheis.wav")
Schema.voices.Add("Combine", "TRACKER", "Tracker.", "npc/combine_soldier/vo/tracker.wav")
Schema.voices.Add("Combine", "TRANSITBLOCK", "Transit-block.", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("Combine", "TROUBLE", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav")
Schema.voices.Add("Combine", "UNDER FIRE", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav")
Schema.voices.Add("Combine", "UNIFORM", "Uniform.", "npc/combine_soldier/vo/uniform.wav")
Schema.voices.Add("Combine", "UNION", "Union!", "npc/metropolice/vo/union.wav")
Schema.voices.Add("Combine", "UNKNOWN", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav")
Schema.voices.Add("Combine", "UP THERE", "He's up there!", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("Combine", "UPI", "UPI.", "npc/metropolice/vo/upi.wav")
Schema.voices.Add("Combine", "UTL SUSPECT", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav")
Schema.voices.Add("Combine", "UTL", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav")
Schema.voices.Add("Combine", "VACATE", "Vacate, citizen!", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("Combine", "VAMP", "Vamp.", "npc/combine_soldier/vo/vamp.wav")
Schema.voices.Add("Combine", "VERDICT", "You want a malcompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
Schema.voices.Add("Combine", "VICE", "Vice!", "npc/metropolice/vo/vice.wav")
Schema.voices.Add("Combine", "VICTOR", "Victor!", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("Combine", "VISCON", "Viscon.", "npc/combine_soldier/vo/viscon.wav")
Schema.voices.Add("Combine", "VISUAL EXOGEN", "Visual on exogen.", "npc/combine_soldier/vo/visualonexogens.wav")
Schema.voices.Add("Combine", "WARNING GIVEN", "Second warning given!", "npc/metropolice/vo/secondwarning.wav")
Schema.voices.Add("Combine", "WASTERIVER", "Wasteriver.", "npc/metropolice/vo/wasteriver.wav")
Schema.voices.Add("Combine", "WATCH IT", "Watch it!", "npc/metropolice/vo/watchit.wav")
Schema.voices.Add("Combine", "WINDER", "Winder.", "npc/combine_soldier/vo/winder.wav")
Schema.voices.Add("Combine", "WORKFORCE", "Workforce intake.", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("Combine", "WRAP IT UP", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("Combine", "XRAY", "XRay!", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("Combine", "YELLOW", "Yellow!", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("Combine", "YOU CAN GO", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("Combine", "ZONE", "Zone!", "npc/metropolice/vo/zone.wav")

Schema.voices.Add("Dispatch", "ACTIVITY LEVEL 1", "You are charged with anti-civil activity level: ONE. Protection-unit prosecution code: DUTY, SWORD, OPERATE.", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "ANTI-CITIZEN", "Attention, ground-units: Anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav", true)
Schema.voices.Add("Dispatch", "ANTI-CIVIL EVIDENCE", "Protection-team, alert: Evidence of anti-civil activity in this community. Code: ASSEMBLE, CLAMP, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "ARE CHARGED WITH", "Individual, you are charged with capital malcompliance. Anti-citizen status, APPROVED.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav", true)
Schema.voices.Add("Dispatch", "INSPECTION POSITIONS", "Attention, please: All citizens in local residential block, assume your inspection-positions.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav", true)
Schema.voices.Add("Dispatch", "AUTONOMOUS JUDGMENT", "Attention, all ground-protection teams, autonomous judgment is now in effect. Sentencing is now discretionary. Code, AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "CITIZEN RELOCATION", "Citizen notice: Failure to co-operate will result in permanent off-world relocation.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav", true)
Schema.voices.Add("Dispatch", "CONSPIRACY", "Citizen reminder: Inaction is conspiracy. Report counter-behavior to a Civil-Protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav", true)
Schema.voices.Add("Dispatch", "CONVICTED", "Individual, you are convicted of multi-anti-civil violations. Implict citizenship revoked. Status, MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav", true)
Schema.voices.Add("Dispatch", "DEDUCTED", "Attention, occupants: Your block is now charged with permissive inactive coersion. Five ration-units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "EVASION BEHAVIOR", "Attention, please, evasion behaviour consistent with malcompliant defendant. Ground protection-team, alert, code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav", true)
Schema.voices.Add("Dispatch", "INDIVIDUAL CHARGED WITH", "Individual, you are charged with socio-endangerment level: ONE. Protection-unit prosecution code, DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "ID CHECK", "Citizen notice, priority identification-check in-progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav", true)
Schema.voices.Add("Dispatch", "JUDGMENT WAIVER", "Attention, all ground-protection teams, judgment waiver now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "MISCOUNT DETECTED", "Attention, residents: Miscount detected in your block. Co-operation with your Civil Protection team permits full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav", true)
Schema.voices.Add("Dispatch", "MISSION FAILURE", "Attention, ground-units: Mission-failure will result in permanent off-world assignment. Code-reminder: SACRIFICE, COAGULATE, CLAMP.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav", true)
Schema.voices.Add("Dispatch", "OVERWATCH ACKNOWLEDGES", "Overwatch acknowledges critical exogen-breach. AirWatch augmentation-force dispatched and inbound. Hold for re-enforcement.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav", true)
Schema.voices.Add("Dispatch", "POTENTIAL INFECTION", "Attention, residents: This blocks contains potential civil infection. INFORM, CO-OPERATE, ASSEMBLE.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav", true)
Schema.voices.Add("Dispatch", "RECEIVE YOUR VERDICT", "Individual, you are now charged with socio-endangerment level: FIVE. Cease evasion immediately, recieve your verdict.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav", true)
Schema.voices.Add("Dispatch", "STATUS EVASION", "Attention, protection-team, status evasion in progress in this community. RESPOND, ISOLATE, INQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNIDENTIFIED", "Attention, please: Unidentified person of interest, confirm your civil status with local protection-team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNREST PROCEDURE", "Attention, community: Unrest procedure code is now in effect. INNOCULATE, SHIELD, PACIFY. Code: PRESSURE, SWORD, STERILIZE.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNREST STRUCTURE", "Alert, community ground-protection units, local unrest structure detected. ASSEMBLE, ADMINISTER, PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav", true)

--[[
Schema.voices.Add("Male Citizen", "DREAM ABOUT CHEESE", "Sometimes, I dream about cheese.", "vo/npc/male01/question06.wav")
Schema.voices.Add("Male Citizen", "CIVIL PROTECTION", "Civil Protection!", "vo/npc/male01/civilprotection01.wav")
Schema.voices.Add("Male Citizen", "YOU ALL OVER", "That's you all over.", "vo/npc/male01/answer01.wav")
Schema.voices.Add("Male Citizen", "HOLD IT AGAINST YOU", "I won't hold it against you.", "vo/npc/male01/answer02.wav")
Schema.voices.Add("Male Citizen", "FIGURES", "Figures.", "vo/npc/male01/answer03.wav")
Schema.voices.Add("Male Citizen", "DWELL ON IT", "Try not to dwell on it.", "vo/npc/male01/answer04.wav")
Schema.voices.Add("Male Citizen", "TALK ABOUT THIS", "Can we talk about this later?", "vo/npc/male01/answer05.wav")
Schema.voices.Add("Male Citizen", "SAME HERE", "Same here.", "vo/npc/male01/answer07.wav")
Schema.voices.Add("Male Citizen", "WHAT YOU MEAN", "Know what you mean.", "vo/npc/male01/answer08.wav")
Schema.voices.Add("Male Citizen", "TALKING TO YOURSELF", "You're talking to yourself again.", "vo/npc/male01/answer09.wav")
Schema.voices.Add("Male Citizen", "SAY TOO LOUD", "I wouldn't say that too loud...", "vo/npc/male01/answer10.wav")
Schema.voices.Add("Male Citizen", "ON YOUR TOMBSTONE", "I'll put it on your tombstone.", "vo/npc/male01/answer11.wav")
Schema.voices.Add("Male Citizen", "BEAR THINKING ABOUT", "Doesn't bear thinking about.", "vo/npc/male01/answer12.wav")
Schema.voices.Add("Male Citizen", "ON WITH YOU", "On with you.", "vo/npc/male01/answer13.wav")
Schema.voices.Add("Male Citizen", "YOU AND ME", "Ha! You and me both.", "vo/npc/male01/answer14.wav")
Schema.voices.Add("Male Citizen", "WAY OF LOOKING", "That's... one way of looking at it.", "vo/npc/male01/answer15.wav")
Schema.voices.Add("Male Citizen", "ORIGINAL THOUGHT", "Have you ever had an.. original thought?", "vo/npc/male01/answer16.wav")
Schema.voices.Add("Male Citizen", "TELL SHUT UP", "I'm not even gonna tell you to shut up.", "vo/npc/male01/answer17.wav")
Schema.voices.Add("Male Citizen", "TASK AT HAND", "Let's concentrate on the task at hand.", "vo/npc/male01/answer18.wav")
Schema.voices.Add("Male Citizen", "MIND ON WORK", "Keep your mind on your work!", "vo/npc/male01/answer19.wav")
Schema.voices.Add("Male Citizen", "IN THE GUTTER", "Your mind is in the gutter.", "vo/npc/male01/answer20.wav")
Schema.voices.Add("Male Citizen", "SURE OF THAT", "Ahh... be so sure of that.", "vo/npc/male01/answer21.wav")
Schema.voices.Add("Male Citizen", "NEVER KNOW", "You never know.", "vo/npc/male01/answer22.wav")
Schema.voices.Add("Male Citizen", "NEVER CAN TELL", "Never can tell.", "vo/npc/male01/answer23.wav")
Schema.voices.Add("Male Citizen", "TELLING ME", "Why are you telling me?", "vo/npc/male01/answer24.wav")
Schema.voices.Add("Male Citizen", "HOW ABOUT THAT", "How about that?", "vo/npc/male01/answer25.wav")
Schema.voices.Add("Male Citizen", "MORE INFORMATION", "That's more information than I require.", "vo/npc/male01/answer26.wav")
Schema.voices.Add("Male Citizen", "WANNA BET", "Haha, wanna bet?", "vo/npc/male01/answer27.wav")
Schema.voices.Add("Male Citizen", "HAD A DIME", "I wish a had a dime for every time somebody said that.", "vo/npc/male01/answer28.wav")
Schema.voices.Add("Male Citizen", "SUPPOSED TO DO", "What am I supposed to do about it?", "vo/npc/male01/answer29.wav")
Schema.voices.Add("Male Citizen", "TALKIN TO ME", "You talkin' to me?", "vo/npc/male01/answer30.wav")
Schema.voices.Add("Male Citizen", "NIP THAT TALK", "You should nip that kind of talk in the bud.", "vo/npc/male01/answer31.wav")
Schema.voices.Add("Male Citizen", "RIGHT ON", "Right on.", "vo/npc/male01/answer32.wav")
Schema.voices.Add("Male Citizen", "NO ARGUMENT THERE", "No argument there.", "vo/npc/male01/answer33.wav")
Schema.voices.Add("Male Citizen", "DONT FORGET HAWAII", "Don't forget Hawaii.", "vo/npc/male01/answer34.wav")
Schema.voices.Add("Male Citizen", "TRY NOT TO", "Try not to let it get to ya.", "vo/npc/male01/answer35.wav")
Schema.voices.Add("Male Citizen", "THE FIRST TIME", "Wouldn't be the first time.", "vo/npc/male01/answer36.wav")
Schema.voices.Add("Male Citizen", "SURE ABOUT THAT", "You sure about that?", "vo/npc/male01/answer37.wav")
Schema.voices.Add("Male Citizen", "LEAVE IT ALONE", "Leave it alone.", "vo/npc/male01/answer38.wav")
Schema.voices.Add("Male Citizen", "ENOUGH OUT OF", "That's enough out of you.", "vo/npc/male01/answer39.wav")
Schema.voices.Add("Male Citizen", "FIRST TIME", "There's a first time for everything.", "vo/npc/male01/answer40.wav")
Schema.voices.Add("Male Citizen", "BEHIND YOU", "Behind you!", "vo/npc/male01/behindyou01.wav")
Schema.voices.Add("Male Citizen", "HI", "Hi.", "vo/npc/male01/hi01.wav")
]]--

Schema.voices.Add("Vortigaunt", "ACCOMPANY", "Gladly we accompany.", "vo/npc/vortigaunt/accompany.wav")
Schema.voices.Add("Vortigaunt", "DEAR TO US", "We have lost all dear to us.", "vo/npc/vortigaunt/alldear.wav")
Schema.voices.Add("Vortigaunt", "ALL FOR NOW", "That is all for now.", "vo/npc/vortigaunt/allfornow.wav")
Schema.voices.Add("Vortigaunt", "ALL IN ONE", "All in one and one in all!", "vo/npc/vortigaunt/allinoneinall.wav")
Schema.voices.Add("Vortigaunt", "ALLOW ME", "Allow me.", "vo/npc/vortigaunt/allowme.wav")
Schema.voices.Add("Vortigaunt", "RECHARGE CELLS", "Allow us to recharge your cells.", "vo/npc/vortigaunt/allowrecharge.wav")
Schema.voices.Add("Vortigaunt", "ALL CAN SPARE", "That is all we can spare.", "vo/npc/vortigaunt/allwecanspare.wav")
Schema.voices.Add("Vortigaunt", "ALL WE HAVE", "All we have is yours.", "vo/npc/vortigaunt/allwehave.wav")
Schema.voices.Add("Vortigaunt", "AS YOU WISH", "As you wish.", "vo/npc/vortigaunt/asyouwish.wav")
Schema.voices.Add("Vortigaunt", "BE OF SERVICE", "Can we be of service?", "vo/npc/vortigaunt/beofservice.wav")
Schema.voices.Add("Vortigaunt", "YOURS TO COMMAND", "This body is yours to command.", "vo/npc/vortigaunt/bodyyours.wav")
Schema.voices.Add("Vortigaunt", "CALM YOURSELF", "Caaaaaaaalm yourself.", "vo/npc/vortigaunt/calm.wav")
Schema.voices.Add("Vortigaunt", "CONVINCE YOU", "Can we not convince you otherwise?", "vo/npc/vortigaunt/canconvince.wav")
Schema.voices.Add("Vortigaunt", "CAUTION", "Caution!", "vo/npc/vortigaunt/caution.wav")
Schema.voices.Add("Vortigaunt", "CERTAINLY", "Certainly.", "vo/npc/vortigaunt/certainly.wav")
Schema.voices.Add("Vortigaunt", "CORPOREAL", "We never dream to meet you in corporeal form.", "vo/npc/vortigaunt/corporeal.wav")
Schema.voices.Add("Vortigaunt", "DEDICATE", "We dedicate ourselves to your purpose.", "vo/npc/vortigaunt/dedicate.wav")
Schema.voices.Add("Vortigaunt", "DONE", "Done.", "vo/npc/vortigaunt/done.wav")
Schema.voices.Add("Vortigaunt", "DREAMED", "We have dreamed of this moment.", "vo/npc/vortigaunt/dreamed.wav")
Schema.voices.Add("Vortigaunt", "EMPOWER", "Empower us!", "vo/npc/vortigaunt/empowerus.wav")
Schema.voices.Add("Vortigaunt", "ENERGY EMPOWERS", "This energy empowers us.", "vo/npc/vortigaunt/energyempower.wav")
Schema.voices.Add("Vortigaunt", "FREEDOM", "For freedom!", "vo/npc/vortigaunt/forfreedom.wav")
Schema.voices.Add("Vortigaunt", "FORWARD", "Give over your essence!", "vo/npc/vortigaunt/giveover.wav")
Schema.voices.Add("Vortigaunt", "GLADLY", "Gladly.", "vo/npc/vortigaunt/gladly.wav")
Schema.voices.Add("Vortigaunt", "GLORIOUS END", "To our glorious end.", "vo/npc/vortigaunt/gloriousend.wav")
Schema.voices.Add("Vortigaunt", "HALT", "Halt.", "vo/npc/vortigaunt/halt.wav")
Schema.voices.Add("Vortigaunt", "HERE", "Here.", "vo/npc/vortigaunt/here.wav")
Schema.voices.Add("Vortigaunt", "HERE WE STAY", "Here we stay.", "vo/npc/vortigaunt/herewestay.wav")
Schema.voices.Add("Vortigaunt", "HOLD.", "Hold.", "vo/npc/vortigaunt/hold.wav")
Schema.voices.Add("Vortigaunt", "HOLD STILL", "Hold still.", "vo/npc/vortigaunt/holdstill.wav")
Schema.voices.Add("Vortigaunt", "TO OUR HONOR", "To our Honor, we follow you.", "vo/npc/vortigaunt/honorfollow.wav")
Schema.voices.Add("Vortigaunt", "HONOR IS OURS", "The honor is ours.", "vo/npc/vortigaunt/honorours.wav")
Schema.voices.Add("Vortigaunt", "HOPELESS", "Our cause seems hopeless.", "vo/npc/vortigaunt/hopeless.wav")
Schema.voices.Add("Vortigaunt", "IF YOU MOVE", "If you move, we cannot help you.", "vo/npc/vortigaunt/ifyoumove.wav")
Schema.voices.Add("Vortigaunt", "HONOR", "It is an honor.", "vo/npc/vortigaunt/itishonor.wav")
Schema.voices.Add("Vortigaunt", "LEAD ON", "Lead on.", "vo/npc/vortigaunt/leadon.wav")
Schema.voices.Add("Vortigaunt", "LEAD US", "Lead us.", "vo/npc/vortigaunt/leadus.wav")
Schema.voices.Add("Vortigaunt", "LIVE TO SERVE", "We live to serve.", "vo/npc/vortigaunt/livetoserve.wav")
Schema.voices.Add("Vortigaunt", "CANNOT HEAL MOVING", "We cannot heal a moving target.", "vo/npc/vortigaunt/movingtarget.wav")
Schema.voices.Add("Vortigaunt", "MUTUAL", "Our purpose is mutual.", "vo/npc/vortigaunt/mutual.wav")
Schema.voices.Add("Vortigaunt", "NEUROPRINTS", "So the neuroprints are true.", "vo/npc/vortigaunt/neuroprints.wav")
Schema.voices.Add("Vortigaunt", "NODE AND NEXUS", "Node and nexus feed upon this life!", "vo/npc/vortigaunt/nodenexus.wav")
Schema.voices.Add("Vortigaunt", "ONWARD", "Onward.", "vo/npc/vortigaunt/onward.wav")
Schema.voices.Add("Vortigaunt", "OPAQUE", "Your mind is opaque.", "vo/npc/vortigaunt/opaque.wav")
Schema.voices.Add("Vortigaunt", "OUR HONOR", "By our honor.", "vo/npc/vortigaunt/ourhonor.wav")
Schema.voices.Add("Vortigaunt", "OUR PLACE HERE", "Our place is here.", "vo/npc/vortigaunt/ourplacehere.wav")
Schema.voices.Add("Vortigaunt", "PASS ON", "Pass on!", "vo/npc/vortigaunt/passon.wav")
Schema.voices.Add("Vortigaunt", "PERSEVERE", "This is more than we can bear, but we will persevere.", "vo/npc/vortigaunt/persevere.wav")
Schema.voices.Add("Vortigaunt", "PLEASURE", "With pleasure.", "vo/npc/vortigaunt/pleasure.wav")
Schema.voices.Add("Free Vortigaunt", "OUR FINEST POET", "Our finest poet describes it thus: Gallum'ba galila ma.", "vo/npc/vortigaunt/poet.wav")
Schema.voices.Add("Vortigaunt", "PREPARE", "Prepare to receive energy.", "vo/npc/vortigaunt/prepare.wav")
Schema.voices.Add("Vortigaunt", "PREVAIL", "We shall prevail.", "vo/npc/vortigaunt/prevail.wav")
Schema.voices.Add("Vortigaunt", "PROPITIOUS", "Propitious alliance.", "vo/npc/vortigaunt/propitious.wav")
Schema.voices.Add("Vortigaunt", "REASON FOR DELAY", "Is there reasob for delay?", "vo/npc/vortigaunt/reasondelay.wav")
Schema.voices.Add("Vortigaunt", "REGRETTABLE", "This is regrettable.", "vo/npc/vortigaunt/regrettable.wav")
Schema.voices.Add("Vortigaunt", "RETURN", "Return to the all in one!", "vo/npc/vortigaunt/returntoall.wav")
Schema.voices.Add("Vortigaunt", "RETURN TO VOID", "Return to the void.", "vo/npc/vortigaunt/returnvoid.wav")
Schema.voices.Add("Vortigaunt", "SATISFACTION", "Satisfaction.", "vo/npc/vortigaunt/satisfaction.wav")
Schema.voices.Add("Vortigaunt", "SURVIVED", "We have survived worse across the ages.", "vo/npc/vortigaunt/seenworse.wav")
Schema.voices.Add("Vortigaunt", "SERVE YOU BETTER", "Perhaps we will serve you better here.", "vo/npc/vortigaunt/servebetterhere.wav")
Schema.voices.Add("Vortigaunt", "STAND CLEAR", "Stand clear!", "vo/npc/vortigaunt/standclear.wav")
Schema.voices.Add("Vortigaunt", "STILL HERE", "We are still here.", "vo/npc/vortigaunt/stillhere.wav")
Schema.voices.Add("Vortigaunt", "SURGE", "We surge!", "vo/npc/vortigaunt/surge.wav")
Schema.voices.Add("Vortigaunt", "TETHER CUT", "The tether is cut!", "vo/npc/vortigaunt/tethercut.wav")
Schema.voices.Add("Vortigaunt", "THAT IS ALL", "That is all.", "vo/npc/vortigaunt/thatisall.wav")
Schema.voices.Add("Vortigaunt", "TO THE VOID", "To the void with you!", "vo/npc/vortigaunt/tothevoid.wav")
Schema.voices.Add("Vortigaunt", "TROUBLE US", "That one shall trouble us no more!", "vo/npc/vortigaunt/troubleus.wav")
Schema.voices.Add("Vortigaunt", "UNDESERVING", "Undeserving of consciousness!", "vo/npc/vortigaunt/undeserving.wav")
Schema.voices.Add("Vortigaunt", "UNCONVINCED", "We remain unconvinced.", "vo/npc/vortigaunt/vanswer01.wav")
Schema.voices.Add("Vortigaunt", "ILLUSIONS", "You are not the first to harbor such illusions.", "vo/npc/vortigaunt/vanswer02.wav")
Schema.voices.Add("Vortigaunt", "OPPOSITE", "We believe the opposite.", "vo/npc/vortigaunt/vanswer03.wav")
Schema.voices.Add("Vortigaunt", "JUST AS WELL", "It is just as well.", "vo/npc/vortigaunt/vanswer04.wav")
Schema.voices.Add("Vortigaunt", "EXPECTED", "We expected as much.", "vo/npc/vortigaunt/vanswer05.wav")
Schema.voices.Add("Vortigaunt", "SPECULATION", "Idle speculation.", "vo/npc/vortigaunt/vanswer06.wav")
Schema.voices.Add("Vortigaunt", "CONCERN", "Your concern is touching.", "vo/npc/vortigaunt/vanswer07.wav")
Schema.voices.Add("Vortigaunt", "DON'T RELY", "Don't rely on it.", "vo/npc/vortigaunt/vanswer08.wav")
Schema.voices.Add("Vortigaunt", "ASSUME NOTHING", "Assume nothing.", "vo/npc/vortigaunt/vanswer09.wav")
Schema.voices.Add("Vortigaunt", "NOTHING OF SORT", "Nothing of the sort.", "vo/npc/vortigaunt/vanswer10.wav")
Schema.voices.Add("Vortigaunt", "DELUDED", "You are deluded.", "vo/npc/vortigaunt/vanswer11.wav")
Schema.voices.Add("Vortigaunt", "WE WISH", "We wish you were right.", "vo/npc/vortigaunt/vanswer12.wav")
Schema.voices.Add("Vortigaunt", "VICISSITUDES", "Excuse our ghost vicissitudes.", "vo/npc/vortigaunt/vanswer13.wav")
Schema.voices.Add("Vortigaunt", "AWARENESS", "We beg your awareness.", "vo/npc/vortigaunt/vanswer14.wav")
Schema.voices.Add("Vortigaunt", "LIKEWISE", "Likewise, we are sure.", "vo/npc/vortigaunt/vanswer15.wav")
Schema.voices.Add("Vortigaunt", "FEELING MUTUAL", "The feeling is mutual.", "vo/npc/vortigaunt/vanswer16.wav")
Schema.voices.Add("Vortigaunt", "UNACCUSTOMED", "This is unaccustomed.", "vo/npc/vortigaunt/vanswer17.wav")
Schema.voices.Add("Vortigaunt", "ALL ONE", "It is all one in the platitude.", "vo/npc/vortigaunt/vanswer18.wavq")
Schema.voices.Add("Vortigaunt", "NO DISTANCE", "There is no distance between us. No false veils of times or space may intervene.", "vo/npc/vortigaunt/vmono_04.wav")
Schema.voices.Add("Vortigaunt", "WOVEN OF VORTESSENCE", "We are a tapestry woven of vortessence. It is the same for you if only you would see it.", "vo/npc/vortigaunt/vmono_27.wav")
Schema.voices.Add("Vortigaunt", "MERELY AN OSCILLATION", "What seems to you a sacrifice is merely to us, an oscillation. We do not fear the interval of darkness.", "vo/npc/vortigaunt/vmono_26.wav")
Schema.voices.Add("Free Vortigaunt", "VORT1", "Ah'Glaa.", "vo/npc/vortigaunt/vortigese02.wav")
Schema.voices.Add("Free Vortigaunt", "VORT2", "Tah.", "vo/npc/vortigaunt/vortigese03.wav")
Schema.voices.Add("Free Vortigaunt", "VORT3", "Dew'it!", "vo/npc/vortigaunt/vortigese04.wav")
Schema.voices.Add("Free Vortigaunt", "VORT4", "Langh.", "vo/npc/vortigaunt/vortigese05.wav")
Schema.voices.Add("Free Vortigaunt", "VORT5", "Gangh.", "vo/npc/vortigaunt/vortigese07.wav")
Schema.voices.Add("Free Vortigaunt", "VORT6", "Gulanga!", "vo/npc/vortigaunt/vortigese08.wav")
Schema.voices.Add("Free Vortigaunt", "VORT7", "Gallah lung.", "vo/npc/vortigaunt/vortigese09.wav")
Schema.voices.Add("Free Vortigaunt", "VORT8", "Churr, galing churr, alla gung.", "vo/npc/vortigaunt/vortigese11.wav")
Schema.voices.Add("Free Vortigaunt", "VORT9", "Churr, langh gangh, chel'el gurr.", "vo/npc/vortigaunt/vortigese12.wav")
Schema.voices.Add("Vortigaunt", "COMBINE WILL PAY", "The Combine will pay in kind for their depravity.", "vo/npc/vortigaunt/vques02.wav")
Schema.voices.Add("Vortigaunt", "HOPE", "Hope is in sight.", "vo/npc/vortigaunt/vques03.wav")
Schema.voices.Add("Vortigaunt", "TURNING POINT", "This marks a turning point.", "vo/npc/vortigaunt/vques04.wav")
Schema.voices.Add("Vortigaunt", "DOOM US ALL", "Such pessimism will doom us all.", "vo/npc/vortigaunt/vques05.wav")
Schema.voices.Add("Vortigaunt", "DARKER TIMES", "We have survived darker times.", "vo/npc/vortigaunt/vques06.wav")
Schema.voices.Add("Free Vortigaunt", "MINDFUL OF WORDS", "We are mindful of the words of our greatest philosopher: Companum genenen vogenant.", "vo/npc/vortigaunt/vques07.wav")
Schema.voices.Add("Vortigaunt", "IN THE QUALITY", "You humans, always in the quality.", "vo/npc/vortigaunt/vques08.wav")
Schema.voices.Add("Vortigaunt", "DEEM COMPANY", "We deem this company inviolable.", "vo/npc/vortigaunt/vques09.wav")
Schema.voices.Add("Vortigaunt", "BELABORED", "Your companionship is dreadly belabored.", "vo/npc/vortigaunt/vques10.wav")
Schema.voices.Add("Vortigaunt", "WHERE", "Where?", "vo/npc/vortigaunt/ware.wav")
Schema.voices.Add("Vortigaunt", "WE ARE YOURS", "We are yours.", "vo/npc/vortigaunt/weareyours.wav")
Schema.voices.Add("Vortigaunt", "WE CLAIM YOU", "We claim you.", "vo/npc/vortigaunt/weclaimyou.wav")
Schema.voices.Add("Vortigaunt", "HONORED", "We are honored.", "vo/npc/vortigaunt/wehonored.wav")
Schema.voices.Add("Vortigaunt", "KNOW YOU", "We know you.", "vo/npc/vortigaunt/wehonored.wav")
Schema.voices.Add("Vortigaunt", "SHARE VORTESSENCE", "We shall share the vortessence.", "vo/npc/vortigaunt/weshare.wav")
Schema.voices.Add("Vortigaunt", "HELP YOU", "We will help you.", "vo/npc/vortigaunt/wewillhelp.wav")
Schema.voices.Add("Vortigaunt", "WHERE TO", "Where to now? And to what end?", "vo/npc/vortigaunt/whereto.wav")
Schema.voices.Add("Vortigaunt", "WE WILL REMAIN", "We will remain, if you so instruct.", "vo/npc/vortigaunt/wewillhelp.wav")
Schema.voices.Add("Vortigaunt", "WORTHLESS", "Our life is worthless unless spent on freedom.", "vo/npc/vortigaunt/worthless.wav")
Schema.voices.Add("Vortigaunt", "YES", "Yessss.", "vo/npc/vortigaunt/yes.wav")
Schema.voices.Add("Vortigaunt", "YES FORWARD", "Yes, forward.", "vo/npc/vortigaunt/yesforward.wav")

Schema.voices.Add("Chumtoad", "RIBBIT 1", "Ribbit.", "npc/chumtoad/toad_deploy1.wav")
Schema.voices.Add("Chumtoad", "RIBBIT 2", "Ribbit.", "npc/chumtoad/toad_hunt1.wav")
Schema.voices.Add("Chumtoad", "MLEM 1", "Mlem.", "npc/chumtoad/toad_hunt2.wav")
Schema.voices.Add("Chumtoad", "MLEM 2", "Mlem.", "npc/chumtoad/toad_hunt3.wav")

Schema.voices.AddClass("Combine", function(client)
	return client:HasBiosignal()
end)

Schema.voices.AddClass("Dispatch", function(client)
	return client:IsDispatch()
end)

Schema.voices.AddClass("Male Citizen", function(client)
	return client:Team() == 3 and !client:IsFemale()
end)

Schema.voices.AddClass("Vortigaunt", function(client)
	return string.find(ix.faction.Get(client:Team()).name, "Vortigaunt") != nil
end)

Schema.voices.AddClass("Free Vortigaunt", function(client)
	return ix.faction.Get(client:Team()).name == "Vortigaunt"
end)

Schema.voices.AddClass("Chumtoad", function(client)
	return client:GetModel() == "models/weapons/half-life/p_chumtoad.mdl" or client:GetModel() == "models/half-life/chumtoad.mdl"
end)

