ITEM.name = "Combine Grenade"
ITEM.description = "A semiflat orange grenade, used exclusively by Combine Grunts."
ITEM.model = "models/hlvr/weapons/grenade/w_grenade.mdl"
ITEM.class = "tfa_combeangren"
ITEM.isGrenade = false
ITEM.weaponCategory = "grenade"
ITEM.canSerial = true
ITEM.cmbWeapon = true
ITEM.width = 1
ITEM.height = 1