ITEM.name = "LA71 (Pulse SMG)"
ITEM.description = "A compact sub-machine gun that fires pulse ammunition."
ITEM.model = "models/hlvr/weapons/ipistol/w_ipistol_hlvr.mdl"
ITEM.class = "tfa_psmg"
ITEM.weaponCategory = "primary"
ITEM.classes = {CLASS_EOW}
ITEM.canGenelock = true
ITEM.canSerial = true
ITEM.cmbWeapon = true
ITEM.width = 3
ITEM.height = 2