ITEM.name = "Smoke Grenade"
ITEM.description = "A cylindrical grenade with gray bands on either end."
ITEM.model = "models/weapons/w_eq_smokegrenade.mdl"
ITEM.class = "weapon_ttt_smokegrenade"
ITEM.weaponCategory = "grenade"
ITEM.isGrenade = true
ITEM.classes = {CLASS_EOW}
ITEM.canSerial = true
ITEM.width = 1
ITEM.height = 1