ITEM.name = "Stormtrooper Helmet Components"
ITEM.desc = "A box of various components for a functioning stormtrooper helmet."
ITEM.uniqueID = "tkhelmetgear"
ITEM.model = "models/starwars/syphadias/props/sw_tor/bioware_ea/items/harvesting/scavenge/scavenge_cargo.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 0
ITEM.category = "Components"
ITEM.recipe = {}
ITEM.cant = 3
