-- Took be about 2 hours. It isn't the best sorry.
Schema.voices.Add("Male Citizen", "BEHIND YOU", "Behind you!", "vo/npc/male01/behindyou0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "BUSY", "Can't you see I'm busy?", "vo/npc/male01/busy02.wav")
Schema.voices.Add("Male Citizen", "CIVIL PROTECTION", "Civil Protection!", "vo/npc/male01/civilprotection0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "COMBINE", "Combine!", "vo/npc/male01/combine0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "COVER ME", "Cover me while I reload!", "vo/npc/male01/coverwhilereload0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "CPS", "CPs!", "vo/npc/male01/cps0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "DOING SOMETHING", "Shouldn't we be, uh, doing something?", "vo/npc/male01/doingsomething.wav")
Schema.voices.Add("Male Citizen", "DREAM ABOUT CHEESE", "Sometimes, I dream about cheese.", "vo/npc/male01/question06.wav")
Schema.voices.Add("Male Citizen", "EVEN ODDS", "Lets even the odds a little.", "vo/npc/male01/evenodds.wav")
Schema.voices.Add("Male Citizen", "EXCUSE ME", "Excuse me.", "vo/npc/male01/excuseme0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "FANTASTIC", "Fantastic.", "vo/npc/male01/fantastic0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "FINALLY", "Finally.", "vo/npc/male01/finally.wav")
Schema.voices.Add("Male Citizen", "GET DOWN", "Get down!", "vo/npc/male01/getdown02.wav")
Schema.voices.Add("Male Citizen", "GET GOING SOON", "Are we gonna get going soon?", "vo/npc/male01/getgoingsoon.wav")
Schema.voices.Add("Male Citizen", "GET THE HELL OUT", "Get the hell out of here!", "vo/npc/male01/gethellout.wav")
Schema.voices.Add("Male Citizen", "GOOD GOD", "Good God.", "vo/npc/male01/goodgod.wav")
Schema.voices.Add("Male Citizen", "GOT ONE", "Got one!", "vo/npc/male01/gotone01.wav")
Schema.voices.Add("Male Citizen", "GOTTA RELOAD", "Gotta reload!", "vo/npc/male01/gottareload01.wav")
Schema.voices.Add("Male Citizen", "GUNSHIP", "Gunship!", "vo/npc/male01/gunship02.wav")
Schema.voices.Add("Male Citizen", "HACKS", "Hacks!", "vo/npc/male01/hacks0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "HA GOT ONE", "Haha, I got one!", "vo/npc/male01/gotone02.wav")
Schema.voices.Add("Male Citizen", "HEADCRABS!", "Headcrabs!", "vo/npc/male01/headcrabs0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "HEADS UP", "Heads up!", "vo/npc/male01/headsup0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "HERE AMMO", "Here, Ammo!", "vo/npc/male01/ammo03.wav")
Schema.voices.Add("Male Citizen", "HELP", "Help!", "vo/npc/male01/help01.wav")
Schema.voices.Add("Male Citizen", "HERE COME THE HACKS", "Here come the Hacks!", "vo/npc/male01/herecomehacks0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "HERE THEY COME", "Here they Come!", "vo/npc/male01/heretheycome01.wav")
Schema.voices.Add("Male Citizen", "HERE TO HELP", "We thought you were here to help!", "vo/npc/male01/heretohelp0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "HERE HAVE A MEDKIT", "Here, have a medkit.", "vo/npc/male01/health04.wav")
Schema.voices.Add("Male Citizen", "HI", "Hi.", "vo/npc/male01/hi0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "HIT IN GUT", "Agh! Hit in the gut!", "vo/npc/male01/hitingut0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "HOLD DOWN THIS SPOT", "I'm gonna stay here and hold down this spot.", "vo/npc/male01/holddownspot0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "TAKE SOME AMMO", "Take some ammo!", "vo/npc/male01/ammo0"..math.random(4,5)..".wav")
Schema.voices.Add("Male Citizen", "TAKE THIS MEDKIT", "Take this medkit.", "vo/npc/male01/health0"..math.random(1,3)..".wav")
Schema.voices.Add("Male Citizen", "TAKE COVER", "Take cover!", "vo/npc/male01/takecover02.wav")
Schema.voices.Add("Male Citizen", "THE HACKS", "The hacks!", "vo/npc/male01/thehacks0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "THIS WILL DO NICELY", "This'll do nicely.", "vo/npc/male01/thislldonicely01.wav")
Schema.voices.Add("Male Citizen", "PATCH YOURSELF UP", "Here, patch yourself up!", "vo/npc/male01/health05.wav")
Schema.voices.Add("Male Citizen", "ILL STAY HERE", "I'll stay here.", "vo/npc/male01/illstayhere01.wav")
Schema.voices.Add("Male Citizen", "IM HURT", "I'm hurt!", "vo/npc/male01/imhurt0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "IM STICKING HERE", "I'm sticking here.", "vo/npc/male01/imstickinghere01.wav")
Schema.voices.Add("Male Citizen", "INCOMING", "Incoming!", "vo/npc/male01/incoming02.wav")
Schema.voices.Add("Male Citizen", "ITS A MANHACK", "It's a manhack!", "vo/npc/male01/itsamanhack01.wav")
Schema.voices.Add("Male Citizen", "LEAD THE WAY", "Lead the way!", "vo/npc/male01/leadtheway0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "LETS GO", "Let's go!", "vo/npc/male01/letsgo0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "LIKE THAT", "Haha, like that?", "vo/npc/male01/likethat.wav")
Schema.voices.Add("Male Citizen", "LITTLE CORNER", "I've got my little corner and I'm sticking to it.", "vo/npc/male01/littlecorner01.wav")
Schema.voices.Add("Male Citizen", "MY ARM", "My arm!", "vo/npc/male01/myarm0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "MY GUT", "Agh! My gut!", "vo/npc/male01/mygut02.wav")
Schema.voices.Add("Male Citizen", "MY LEG", "My leg!", "vo/npc/male01/myleg0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "NICE", "Nice.", "vo/npc/male01/nice.wav")
Schema.voices.Add("Male Citizen", "NOO", "Nooooo!", "vo/npc/male01/no0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "OH NO", "Oh no.", "vo/npc/male01/ohno.wav")
Schema.voices.Add("Male Citizen", "OK", "Okay.", "vo/npc/male01/ok0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "OK IM READY", "Okay, I'm ready.", "vo/npc/male01/okimready0"..math.random(1,3)..".wav")
Schema.voices.Add("Male Citizen", "ONE FOR ME", "One for me and one.. for me!", "vo/npc/male01/oneforme.wav")
Schema.voices.Add("Male Citizen", "OUT OF YOUR WAY", "Let me get out of your way.", "vo/npc/male01/outofyourway02.wav")
Schema.voices.Add("Male Citizen", "OVER HERE", "Hey, over here!", "vo/npc/male01/overhere01.wav")
Schema.voices.Add("Male Citizen", "OVER THERE", "Over there!", "vo/npc/male01/overthere0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "OW", "Ow!", "vo/npc/male01/ow0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "PARDON ME", "Pardon me.", "vo/npc/male01/pardonme0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "READY WHEN YOU ARE", "Ready when you are!", "vo/npc/male01/readywhenyouare01.wav")
Schema.voices.Add("Male Citizen", "RUN FOR YOUR LIFE", "Run for your Life!", "vo/npc/male01/runforyourlife0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "RUN", "Ruuuuun!", "vo/npc/male01/strider_run.wav")
Schema.voices.Add("Male Citizen", "SCANNERS", "Scanners!", "vo/npc/male01/scanners0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "SORRY", "Sorry.", "vo/npc/male01/sorry0"..math.random(1,3)..".wav")
Schema.voices.Add("Male Citizen", "STRIDER", "Strider!", "vo/npc/male01/strider.wav")
Schema.voices.Add("Male Citizen", "UH OH", "Uh oh.", "vo/npc/male01/uhoh.wav")
Schema.voices.Add("Male Citizen", "UP THERE", "Up there.", "vo/npc/male01/upthere0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "WAITING FOR SOMEBODY", "You waiting for somebody?", "vo/npc/male01/waitingsomebody.wav")
Schema.voices.Add("Male Citizen", "WATCH OUT", "Watch out!", "vo/npc/male01/watchout.wav")
Schema.voices.Add("Male Citizen", "WATCH WHAT YOU ARE DOING", "Watch what you're doing!", "vo/npc/male01/watchwhat.wav")
Schema.voices.Add("Male Citizen", "WE TRUSTED YOU", "We trusted you!", "vo/npc/male01/wetrustedyou0"..math.random(1,2)..".wav")
Schema.voices.Add("Male Citizen", "WHOOPS", "Whoops.", "vo/npc/male01/whoops01.wav")
Schema.voices.Add("Male Citizen", "YEAH", "Yeah.", "vo/npc/male01/yeah02.wav")
Schema.voices.Add("Male Citizen", "YOU BETTER RELOAD", "You better reload.", "vo/npc/male01/youdbetterreload01.wav")
Schema.voices.Add("Male Citizen", "YOU GOT IT", "You got it.", "vo/npc/male01/yougotit02.wav")
Schema.voices.Add("Male Citizen", "ZOMBIES", "Zombies!", "vo/npc/male01/zombies0"..math.random(1,2)..".wav")

Schema.voices.Add("Female Citizen", "BEHIND YOU", "Behind you!", "vo/npc/Female01/behindyou0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "BUSY", "Can't you see that I'm busy?", "vo/npc/Female01/busy02.wav")
Schema.voices.Add("Female Citizen", "CIVIL PROTECTION", "Civil Protection!", "vo/npc/Female01/civilprotection0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "COMBINE", "Combine!", "vo/npc/Female01/combine0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "COVER ME", "Cover me while I reload!", "vo/npc/Female01/coverwhilereload0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "CPS", "CPs!", "vo/npc/Female01/cps0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "DOING SOMETHING", "Shouldn't we be, uh, doing something?", "vo/npc/Female01/doingsomething.wav")
Schema.voices.Add("Female Citizen", "DREAM ABOUT CHEESE", "Sometimes, I dream about cheese.", "vo/npc/Female01/question06.wav")
Schema.voices.Add("Female Citizen", "EVEN ODDS", "Lets even the odds a little.", "vo/npc/Female01/evenodds.wav")
Schema.voices.Add("Female Citizen", "EXCUSE ME", "Excuse me.", "vo/npc/Female01/excuseme0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "FANTASTIC", "Fantastic.", "vo/npc/Female01/fantastic0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "FINALLY", "Finally.", "vo/npc/Female01/finally.wav")
Schema.voices.Add("Female Citizen", "GET DOWN", "Get down!", "vo/npc/Female01/getdown02.wav")
Schema.voices.Add("Female Citizen", "GET GOING SOON", "Are we gonna get going soon?", "vo/npc/Female01/getgoingsoon.wav")
Schema.voices.Add("Female Citizen", "GET THE HELL OUT", "Get the hell out of here!", "vo/npc/Female01/gethellout.wav")
Schema.voices.Add("Female Citizen", "GOOD GOD", "Good God.", "vo/npc/Female01/goodgod.wav")
Schema.voices.Add("Female Citizen", "GOT ONE", "Got one!", "vo/npc/Female01/gotone01.wav")
Schema.voices.Add("Female Citizen", "GOTTA RELOAD", "Gotta reload!", "vo/npc/Female01/gottareload01.wav")
Schema.voices.Add("Female Citizen", "GUNSHIP", "Gunship!", "vo/npc/Female01/gunship02.wav")
Schema.voices.Add("Female Citizen", "HACKS", "Hacks!", "vo/npc/Female01/hacks0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "HAH GOT ONE", "Haha, I got one!", "vo/npc/Female01/gotone02.wav")
Schema.voices.Add("Female Citizen", "HEADCRABS", "Headcrabs!", "vo/npc/Female01/headcrabs0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "HEADS UP", "Heads up!", "vo/npc/Female01/headsup0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "HERE AMMO", "Here Ammo!", "vo/npc/Female01/ammo03.wav")
Schema.voices.Add("Female Citizen", "HELP", "Help!", "vo/npc/Female01/help01.wav")
Schema.voices.Add("Female Citizen", "HERE COME THE HACKS", "Here come the hacks!", "vo/npc/Female01/herecomehacks0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "HERE THEY COME", "Here they come!", "vo/npc/Female01/heretheycome01.wav")
Schema.voices.Add("Female Citizen", "HERE TO HELP", "We thought you were here to help!", "vo/npc/Female01/heretohelp0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "HERE HAVE A MEDKIT", "Here have a medkit.", "vo/npc/Female01/health04.wav")
Schema.voices.Add("Female Citizen", "HI", "Hi.", "vo/npc/Female01/hi0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "HIT IN GUT", "Agh! Hit in the gut!", "vo/npc/Female01/hitingut0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "HOLD DOWN THIS SPOT", "I'm gonna stay here and hold down this spot.", "vo/npc/Female01/holddownspot0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "TAKE SOME AMMO", "Take some ammo!", "vo/npc/Female01/ammo0"..math.random(4,5)..".wav")
Schema.voices.Add("Female Citizen", "TAKE THIS MEDKIT", "Take this medkit.", "vo/npc/Female01/health0"..math.random(1,3)..".wav")
Schema.voices.Add("Female Citizen", "TAKE COVER", "Take cover!", "vo/npc/Female01/takecover02.wav")
Schema.voices.Add("Female Citizen", "THE HACKS", "The hacks!", "vo/npc/Female01/thehacks0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "THIS WILL DO NICELY", "This'll do nicely.", "vo/npc/Female01/thislldonicely01.wav")
Schema.voices.Add("Female Citizen", "PATCH YOURSELF UP", "Here, patch yourself up!", "vo/npc/Female01/health05.wav")
Schema.voices.Add("Female Citizen", "ILL STAY HERE", "I'll stay here.", "vo/npc/Female01/illstayhere01.wav")
Schema.voices.Add("Female Citizen", "IM HURT", "I'm hurt!", "vo/npc/Female01/imhurt0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "IM STICKING HERE", "I'm sticking here.", "vo/npc/Female01/imstickinghere01.wav")
Schema.voices.Add("Female Citizen", "INCOMING", "Incoming!", "vo/npc/Female01/incoming02.wav")
Schema.voices.Add("Female Citizen", "ITS A MANHACK", "It's a manhack!", "vo/npc/Female01/itsamanhack01.wav")
Schema.voices.Add("Female Citizen", "LEAD THE WAY", "Lead the way!", "vo/npc/Female01/leadtheway0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "LETS GO", "Let's go!", "vo/npc/Female01/letsgo0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "LIKE THAT", "Haha, like that?", "vo/npc/Female01/likethat.wav")
Schema.voices.Add("Female Citizen", "LITTLE CORNER", "I've got my little corner and I'm sticking to it.", "vo/npc/Female01/littlecorner01.wav")
Schema.voices.Add("Female Citizen", "MY ARM", "My arm!", "vo/npc/Female01/myarm0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "MY GUT", "Agh! My gut!", "vo/npc/Female01/mygut02.wav")
Schema.voices.Add("Female Citizen", "MY LEG", "My leg!", "vo/npc/Female01/myleg0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "NICE", "Nice.", "vo/npc/Female01/nice.wav")
Schema.voices.Add("Female Citizen", "NOO", "Nooooo!", "vo/npc/Female01/no0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "OH NO", "Oh no.", "vo/npc/Female01/ohno.wav")
Schema.voices.Add("Female Citizen", "OK", "Ok.", "vo/npc/Female01/ok0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "OK IM READY", "Okay, I'm ready.", "vo/npc/Female01/okimready0"..math.random(1,3)..".wav")
Schema.voices.Add("Female Citizen", "ONE FOR ME", "One for me and one.. for me!", "vo/npc/Female01/oneforme.wav")
Schema.voices.Add("Female Citizen", "OUT OF YOUR WAY", "Let me get out of your way.", "vo/npc/Female01/outofyourway02.wav")
Schema.voices.Add("Female Citizen", "OVER HERE", "Hey, over here!", "vo/npc/Female01/overhere01.wav")
Schema.voices.Add("Female Citizen", "OVER THERE", "Over there!", "vo/npc/Female01/overthere0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "OW", "Ow!", "vo/npc/Female01/ow0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "PARDON ME", "Pardon me.", "vo/npc/Female01/pardonme0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "READY WHEN YOU ARE", "Ready when you are!", "vo/npc/Female01/readywhenyouare01.wav")
Schema.voices.Add("Female Citizen", "RUN FOR YOUR LIFE", "Run for your life!", "vo/npc/Female01/runforyourlife0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "RUN", "Ruuuuun!", "vo/npc/Female01/strider_run.wav")
Schema.voices.Add("Female Citizen", "SCANNERS", "Scanners!", "vo/npc/Female01/scanners0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "SORRY", "Sorry.", "vo/npc/Female01/sorry0"..math.random(1,3)..".wav")
Schema.voices.Add("Female Citizen", "STRIDER", "Strider!", "vo/npc/Female01/strider.wav")
Schema.voices.Add("Female Citizen", "UH OH", "Uh oh.", "vo/npc/Female01/uhoh.wav")
Schema.voices.Add("Female Citizen", "UP THERE", "Up there.", "vo/npc/Female01/upthere0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "WAITING FOR SOMEBODY", "You waiting for somebody?", "vo/npc/Female01/waitingsomebody.wav")
Schema.voices.Add("Female Citizen", "WATCH OUT", "Watch out!", "vo/npc/Female01/watchout.wav")
Schema.voices.Add("Female Citizen", "WATCH WHAT YOU ARE DOING", "Watch what you're doing!", "vo/npc/Female01/watchwhat.wav")
Schema.voices.Add("Female Citizen", "WE TRUSTED YOU", "We trusted you!", "vo/npc/Female01/wetrustedyou0"..math.random(1,2)..".wav")
Schema.voices.Add("Female Citizen", "WHOOPS", "Whoops.", "vo/npc/Female01/whoops01.wav")
Schema.voices.Add("Female Citizen", "YEAH", "Yeah.", "vo/npc/Female01/yeah02.wav")
Schema.voices.Add("Female Citizen", "YOU BETTER RELOAD", "You better reload.", "vo/npc/Female01/youdbetterreload01.wav")
Schema.voices.Add("Female Citizen", "YOU GOT IT", "You got it.", "vo/npc/Female01/yougotit02.wav")
Schema.voices.Add("Female Citizen", "ZOMBIES", "Zombies!", "vo/npc/Female01/zombies0"..math.random(1,2)..".wav")

Schema.voices.AddClass("Male Citizen", function(client)
	if !client:IsFemale(client:GetModel()) then
		return client:Team() == FACTION_CITIZEN
	end
end)

Schema.voices.AddClass("Female Citizen", function(client)
	if client:IsFemale(client:GetModel()) then
		return client:Team() == FACTION_CITIZEN
	end
end)